cursor            #c7c3e1
cursor_text_color #302e45

foreground            #e5e1e4
background            #0e0e10
selection_foreground  #312f39
selection_background  #c8c5d2
url_color             #c8c5d2

#: black 000000 767676
color0  #141315
color8  #353436
#: red cc0403 f2201f
color1  #000000
color9  #373457
#: green 19cb00 23fd00
color2  #c8c5d2
color10 #e5e0ee
#: yellow cecb00 fffd00
color3  #e2bcce
color11 #ffd8ea
#: blue 0d73cc 1a8fff
color4  #46445c
color12 #c7c3e1
#: magenta cb1ed1 fd28ff
color5  #474550
color13 #c8c5d2
#: cyan 0dcdcd 14ffff
color6  #5a3f4d
color14 #e2bcce
#: white dddddd ffffff
color7  #c9c5cd
color15 #e5e1e4

mark1_foreground #1b192f
mark1_background #e4dffd
mark2_foreground #1c1a24
mark2_background #e5e0ee
mark3_foreground #2b1421
mark3_background #ffd8ea

active_tab_foreground #302e45
active_tab_background #c7c3e1
inactive_tab_foreground #bebad7
inactive_tab_background #2f2d44

active_border_color #c7c3e1
inactive_border_color #302e45
# bell_border_color #ff5a00
